// Generated by CoffeeScript 1.10.0
(function() {
  var GITURL, loadFonts, render, setColorTheme, setCssFont, setStatus;

  GITURL = "https://cdn.rawgit.com/kba/figlet-fonts/gh-pages";

  figlet.defaults({
    fontPath: GITURL + "/fonts"
  });

  loadFonts = function(cb) {
    var fonts;
    fonts = [];
    return $.get(GITURL + "/fontlist.txt", function(textlist) {
      var font, i, len, ref;
      ref = textlist.split('\n');
      for (i = 0, len = ref.length; i < len; i++) {
        font = ref[i];
        font = font.replace(/\..*$/, '');
        $("#font").append($("<option>").html(font));
      }
      return cb();
    });
  };

  setCssFont = function() {
    console.log($("#font-family").val());
    return $("#output").css('font-family', $("#font-family").val());
  };

  setColorTheme = function() {
    return $("#output").attr('data-color-theme', $("#color-theme").val());
  };

  setStatus = function(status) {
    return $("#status").attr("data-status", status).html(status);
  };

  render = function() {
    setStatus('wait');
    return figlet($("#input").val(), $("#font :selected").text(), function(err, text) {
      if (err) {
        setStatus('err');
        return console.log(err);
      }
      setStatus('ok');
      return $("#output").html(text);
    });
  };

  loadFonts(function() {
    $("#input").on('input', render);
    $("#font").on('change', render);
    $("#color-theme").on('change', setColorTheme);
    $("#font-family").on('input', setCssFont);
    $("#input").removeAttr('disabled');
    $("#font").val('standard');
    setStatus("wait");
    setColorTheme();
    return setCssFont();
  });

}).call(this);
