// Generated by CoffeeScript 1.10.0
(function() {
  var render;

  figlet.defaults({
    fontPath: '../fonts'
  });

  $(function() {
    var fonts;
    fonts = [];
    $.get('fontlist.txt', function(textlist) {
      var font, i, len, ref;
      ref = textlist.split('\n');
      for (i = 0, len = ref.length; i < len; i++) {
        font = ref[i];
        font = font.replace(/\..*$/, '');
        $("#font").append($("<option>").html(font));
      }
      return $("#font").val('standard');
    });
    $("#input").on('input', render);
    return $("#font").on('change', render);
  });

  render = function() {
    return figlet($("#input").val(), $("#font :selected").text(), function(err, text) {
      if (err) {
        return console.log(err);
      }
      console.log(text);
      return $("#output").html(text);
    });
  };

}).call(this);
